CREATE DATABASE HOTEL;
USE HOTEL;

-- CREATE TABLE ACCOUNT(
-- SN INT,
-- ID INT PRIMARY KEY,
-- NAME VARCHAR(15),
-- SALARY INT
-- );

-- INSERT INTO ACCOUNT VALUES
-- (1, 101,"PRAYAS" ,15000),
-- (2,102, "RAM" ,10000);

-- INSERT INTO ACCOUNT VALUE(3,103,"SHUAM",5000);

-- SELECT * FROM ACCOUNT;
-- DROP TABLE IF exists ACCOUNT;
-- DROP DATABASE IF exists PRAYFGGFGAS;


-- UNIQUE 

-- CREATE TABLE TEMP(
-- ID INT  UNIQUE
-- );

-- INSERT INTO TEMP VALUES
-- (101),
-- (101);  --IT WONT WORK DUE TO UNIQUE ENLISTED IN THE CONSTRAINTS

-- SELECT * FROM TEMP;



-- PRIMARY KEY

-- CREATE TABLE PRIMARY0 (
-- ID INT,
-- NAME VARCHAR(10),
-- CITY VARCHAR(10)
-- PRIMARY KEY (ID , NAME)  -- IT MEANS ID & NAME WONT BE SIMILAR ONE MUST BE DIFFERENT FROM EACH OTHER
-- );


-- DEFAULT

-- CREATE TABLE DEFAULT2 (
-- ID INT,
-- SALARY INT DEFAULT 25000  -- WILL PROVIDE DEFAULT VALUE OF 25000 IN EACH SECTION.
-- );

-- INSERT INTO DEFAULT2 (ID) value (101);
-- select * FROM DEFAULT2;


-- USE OF SELECT

CREATE TABLE SELECTT (
ROLLNB INT PRIMARY KEY,
NAME VARCHAR(20),
MARKS INT NOT NULL,
GRADE VARCHAR(5),
CITY VARCHAR(10)
);

INSERT INTO SELECTT VALUES
(1,"ANIL",1,"C","KTM"),
(2,"ANIL",78,"C","KTM"),
(3,"ANIL",100,"C","KTM"),
(4,"ANIL",34,"C","KTM"),
(5,"ANIL",23,"C","SINDHULI"),
(6,"ANIL",50,"C","KTM");

SELECT NAME, MARKS FROM SELECTT;  -- ONLY SELECT THE SPECIFIC COLUMN
SELECT * FROM SELECTT;
SELECT distinct CITY FROM SELECTT;  -- DOESNT REPEAT THE VALUES
SELECT * FROM SELECTT WHERE MARKS >50;  --  PROVIDES CONDITION & RETURN ONLY WHAT THE  CONDITON IS
SELECT * FROM SELECTT WHERE CITY = "SINDHULI";
SELECT * FROM SELECTT WHERE MARKS >20 AND CITY = "SINDHULI";
DROP TABLE SELECTT;
SELECT * FROM SELECTT ORDER BY CITY ASC;  -- ASCENDING ORDER
SELECT * FROM SELECTT ORDER BY MARKS DESC;


-- AGGREGATE FUNCTIONS
SELECT MAX(MARKS) FROM SELECTT;
SELECT AVG(MARKS) FROM SELECTT;





