CREATE DATABASE HOTEL;
USE HOTEL;

-- CREATE TABLE ACCOUNT(
-- SN INT,
-- ID INT PRIMARY KEY,
-- NAME VARCHAR(15),
-- SALARY INT
-- );

-- INSERT INTO ACCOUNT VALUES
-- (1, 101,"PRAYAS" ,15000),
-- (2,102, "RAM" ,10000);

-- INSERT INTO ACCOUNT VALUE(3,103,"SHUAM",5000);

-- SELECT * FROM ACCOUNT;
-- DROP TABLE IF exists ACCOUNT;
-- DROP DATABASE IF exists PRAYFGGFGAS;


-- UNIQUE 

-- CREATE TABLE TEMP(
-- ID INT  UNIQUE
-- );

-- INSERT INTO TEMP VALUES
-- (101),
-- (101);  --IT WONT WORK DUE TO UNIQUE ENLISTED IN THE CONSTRAINTS

-- SELECT * FROM TEMP;



-- PRIMARY KEY

-- CREATE TABLE PRIMARY0 (
-- ID INT,
-- NAME VARCHAR(10),
-- CITY VARCHAR(10)
-- PRIMARY KEY (ID , NAME)  -- IT MEANS ID & NAME WONT BE SIMILAR ONE MUST BE DIFFERENT FROM EACH OTHER
-- );


-- DEFAULT

-- CREATE TABLE DEFAULT2 (
-- ID INT,
-- SALARY INT DEFAULT 25000  -- WILL PROVIDE DEFAULT VALUE OF 25000 IN EACH SECTION.
-- );

-- INSERT INTO DEFAULT2 (ID) value (101);
-- select * FROM DEFAULT2;


-- USE OF SELECT

-- CREATE TABLE SELECTT (
-- ROLLNB INT PRIMARY KEY,
-- NAME VARCHAR(20),
-- MARKS INT NOT NULL,
-- GRADE VARCHAR(5),
-- CITY VARCHAR(10)
-- );

-- INSERT INTO SELECTT VALUES
-- (1,"ANIL",1,"C","KTM"),
-- (2,"ANIL",78,"C","KTM"),
-- (3,"ANIL",100,"C","KTM"),
-- (4,"ANIL",34,"C","KTM"),
-- (5,"ANIL",23,"C","SINDHULI"),
-- (6,"ANIL",50,"C","KTM");

-- SELECT NAME, MARKS FROM SELECTT;  -- ONLY SELECT THE SPECIFIC COLUMN
-- SELECT * FROM SELECTT;
-- SELECT distinct CITY FROM SELECTT;  -- DOESNT REPEAT THE VALUES
-- SELECT * FROM SELECTT WHERE MARKS >50;  --  PROVIDES CONDITION & RETURN ONLY WHAT THE  CONDITON IS
-- SELECT * FROM SELECTT WHERE CITY = "SINDHULI";
-- SELECT * FROM SELECTT WHERE MARKS >20 AND CITY = "SINDHULI";
-- DROP TABLE SELECTT;
-- SELECT * FROM SELECTT ORDER BY CITY ASC;  -- ASCENDING ORDER
-- SELECT * FROM SELECTT ORDER BY MARKS DESC;


-- -- AGGREGATE FUNCTIONS
-- SELECT MAX(MARKS) FROM SELECTT;
-- SELECT AVG(MARKS) FROM SELECTT;


-- update 

-- CREATE TABLE PERSONAL(
-- ID INT PRIMARY KEY,
-- NAME VARCHAR(15),
-- PERCENTAGE INT,
-- AGE INT,
-- GENDER VARCHAR(10)
-- );

-- INSERT INTO PERSONAL VALUES
-- (1,"PRAYAS",90,20,"M"),
-- (2,"SUYOG",91,20,"M"),
-- (3,"BEDRAJ",92,20,"M"),
-- (4,"DIPENDRA",93,20,"M"),
-- (5,"SUSHAN",94,20,"M"),
-- (6,"OM",97,27,"M"),
-- (7,"BISHAL",96,20,"M");

-- SELECT * FROM PERSONAL;
-- UPDATE PERSONAL 
-- SET PERCENTAGE = 99
-- WHERE ID = 6;


-- -- FOREIGN KEY:

-- CREATE TABLE CITY 
-- (
--     ID INT PRIMARY KEY,
--     CITYNAME VARCHAR(20)
-- );

-- INSERT INTO CITY VALUES
-- (1,"KTM"),
-- (2,"BUDHANILKANTHA"),
-- (3,"SINDHULI"),
-- (4,"DANDATOLE");

-- CREATE TABLE STUDENTTTTTTT
-- (
--     ID INT PRIMARY KEY,
--     NAME VARCHAR(20),
--     CITYID INT,
--     FOREIGN KEY (CITYID) REFERENCES CITY (ID)
-- );

-- INSERT INTO STUDENTTTTTTT VALUES
-- (101,"KARAN",1),
-- (102,"SUYOG",2),
-- (103,"BED",4),
-- (104,"OM",3);

-- DROP TABLE CITY;
-- drop TABLE STUDENTTTTTTT;
-- SELECT * FROM CITY;
-- SELECT * FROM STUDENTTTTTTT;

CREATE TABLE STUDENTSSSSSS
(
STU_ID INT PRIMARY KEY,
STU_NAME VARCHAR(20),
STU_ADDRESS VARCHAR(20),
DEPT_ID INT,
AGE INT
);

INSERT INTO STUDENTSSSSSS VALUES
(10, "MAYA", "PALPA",1,21),
(11, "ABIN", "KTM",2,2),
(12, "AARAR", "KTM",1,26),
(13, "ASHNA", "SINDHULI",3,61),
(14, "ANUJ","POKHARAPA",4,11),
(15, "MAINSH", "BANEPA",2,41),
(16, "MAYA", "KTM",1,51);

SELECT STU_NAME, STU_ADDRESS FROM STUDENTSSSSSS;
SELECT STU_NAME, DEPT_ID FROM STUDENTSSSSSS where DEPT_ID =1;
SELECT STU_NAME,DEPT_ID FROM STUDENTSSSSSS WHERE STU_ADDRESS = "KTM";
SELECT STU_NAME,STU_ADDRESS FROM STUDENTSSSSSS WHERE STU_ADDRESS != "KTM";

SELECT STU_NAME,DEPT_ID FROM STUDENTSSSSSS WHERE (DEPT_ID > 2);
SELECT STU_NAME,DEPT_ID FROM STUDENTSSSSSS WHERE (DEPT_ID >= 2);
SELECT STU_NAME,DEPT_ID FROM STUDENTSSSSSS WHERE STU_ADDRESS = "KTM" AND DEPT_ID <>1;  -- NOT EQUAL TO




